image:
  name: gscloudsolutions/devops-mate:stable #Referencing the public image from Docker Hub
  #username: $DOCKER_HUB_USERNAME #Username-password not required
  #password: $DOCKER_HUB_PASSWORD

pipelines:
  pull-requests:
      feature/*: #any branch with a feature prefix
        - step:
            name: Creating Deployment Package for CI(Continuous Integration)/QA Org
            script:
              - echo 'Getting Target Org Status From QA/Partial Dev Org'
              - sfDeploymentInfo get -u "$QA_ORG_USERNAME" -t $QA_ORG_TYPE -i $BITBUCKET_BUILD_NUMBER -n All -s "$QA_ORG_PASSWORD"
              - echo 'Creating a Git Diff based artifact/package'
              - sfPackages mdapi -p $BITBUCKET_CLONE_DIR -n $LATEST_COMMIT_HASH_TAG -i $BITBUCKET_BUILD_NUMBER || if test $? -eq 21; then exit 0; else exit 1; fi
            artifacts:
              - Artifacts/**
        - step:
            name: Scratch Org Creation and Deployment
            script:
              - echo 'Create Scratch Org'
              - echo 'Deploy to Scratch Org'
        - step:
            name: Deployment Validation On QA/CI Org
            script:
              - echo 'Getting Target Org Status From QA/Partial Dev Org'
              - sfDeploymentInfo get -u "$QA_ORG_USERNAME" -t $QA_ORG_TYPE -i $BITBUCKET_BUILD_NUMBER -n All -s "$QA_ORG_PASSWORD"
              #- echo 'Creating a Git Diff based artifact/package'
              #- sfPackages source-combined -p $BITBUCKET_CLONE_DIR/$QA_PACKAGE_DIR -n $LATEST_COMMIT_HASH_TAG -i $BITBUCKET_BUILD_NUMBER || if test $? -eq 21; then exit 0; else exit 1; fi
              - echo 'Deployment Validation On QA/CI Org.'
              - sfDeploy mdapipackage -p $BITBUCKET_CLONE_DIR -c true -u "$QA_ORG_USERNAME" -s "$QA_ORG_PASSWORD" -t $QA_ORG_TYPE --successSHA $LATEST_COMMIT_HASH_TAG -i $BITBUCKET_BUILD_NUMBER
            artifacts:
              - Artifacts/**
  branches:
    # Pipeline for master branch
    'master':
      #Automated step as BB Pipeline can not start with a manual step
      - step:
          name: Feature Ready for QA
          script:
             - echo 'Ready for QA'
      #QA Org Deployment
      - step:
          name: QA Org Deployment
          deployment: QAOrg
          #trigger: manual
          script:
            - echo 'Getting Target Org Status From QA Org'
            - sfDeploymentInfo get -u "$QA_ORG_USERNAME" -t $QA_ORG_TYPE -i $BITBUCKET_BUILD_NUMBER -n All -s "$QA_ORG_PASSWORD"
            - echo 'Creating a Git Diff based artifact/package'
            - sfPackages mdapi -p $BITBUCKET_CLONE_DIR -n $LATEST_COMMIT_HASH_TAG -i $BITBUCKET_BUILD_NUMBER || if test $? -eq 21; then exit 0; else exit 1; fi
            - echo 'Deployment On QA Org.'
            - sfDeploy mdapipackage -p $BITBUCKET_CLONE_DIR -u "$QA_ORG_USERNAME" -s "$QA_ORG_PASSWORD" -t $QA_ORG_TYPE --successSHA $LATEST_COMMIT_HASH_TAG -i $BITBUCKET_BUILD_NUMBER -l RunLocalTests
      #UAT Org Deployment 
      - step:
          name: UAT Org Deployment
          deployment: UATOrg
          trigger: manual
          script:
            - echo 'Getting Target Org Status from UAT Org'
            - sfDeploymentInfo get -u "$UAT_ORG_USERNAME" -t $UAT_ORG_TYPE -i $BITBUCKET_BUILD_NUMBER -n All -s "$UAT_ORG_PASSWORD"
            - echo 'Creating a Git Diff based artifact/package'
            - sfPackages mdapi -p $BITBUCKET_CLONE_DIR -n $LATEST_COMMIT_HASH_TAG -i $BITBUCKET_BUILD_NUMBER || if test $? -eq 21; then exit 0; else exit 1; fi
            - echo 'UAT Org Deployment Validation'
            - sfDeploy mdapipackage -p $BITBUCKET_CLONE_DIR -u "$UAT_ORG_USERNAME" -s "$UAT_ORG_PASSWORD" -t $UAT_ORG_TYPE --successSHA $LATEST_COMMIT_HASH_TAG -i $BITBUCKET_BUILD_NUMBER -l RunLocalTests
          artifacts:
            - Artifacts/**
      #Production Org Deployment Validation
      - step:
          name: Creating Deployment Package for Production Org Validation
          script: 
            - echo 'Getting Target Org Status from Production Org'
            - sfDeploymentInfo get -u "$PROD_ORG_USERNAME" -t "$PROD_ORG_TYPE" -i $BITBUCKET_BUILD_NUMBER -n All -s "$PROD_ORG_PASSWORD"
            - echo 'Creating a Git Diff based artifact/package'
            - sfPackages mdapi -p $BITBUCKET_CLONE_DIR -n $LATEST_COMMIT_HASH_TAG -i $BITBUCKET_BUILD_NUMBER || if test $? -eq 21; then exit 0; else exit 1; fi
          artifacts:
            - Artifacts/**
      - step:
          name: Prod Org Deployment Validation
          trigger: manual
          script:
            - echo 'Getting Target Org Status from Production Org'
            - sfDeploymentInfo get -u $PROD_ORG_USERNAME -t $PROD_ORG_TYPE -i $BITBUCKET_BUILD_NUMBER -n All -s $PROD_ORG_PASSWORD
            - echo 'Creating a Git Diff based artifact/package'
            - sfPackages mdapi -p $BITBUCKET_CLONE_DIR/$PROD_PACKAGE_DIR -n $LATEST_COMMIT_HASH_TAG -i $BITBUCKET_BUILD_NUMBER || if test $? -eq 21; then exit 0; else exit 1; fi
            - echo 'Production Org Deployment Validation'
            - sfDeploy mdapipackage -p $BITBUCKET_CLONE_DIR/$PROD_PACKAGE_DIR -c true -u $PROD_ORG_USERNAME -s $PROD_ORG_PASSWORD -t $PROD_ORG_TYPE --successSHA $LATEST_COMMIT_HASH_TAG -i $BITBUCKET_BUILD_NUMBER -l RunLocalTests
      #Production Org Deployment
      - step:
          name: Prod Org Deployment
          deployment: ProdOrg
          trigger: manual
          script:
            - echo 'Getting Target Org Status from Production Org'
            - sfDeploymentInfo get -u "$PROD_ORG_USERNAME" -t $PROD_ORG_TYPE -i $BITBUCKET_BUILD_NUMBER -n All -s "$PROD_ORG_PASSWORD"
            - echo 'Creating a Git Diff based artifact/package'
            - sfPackages mdapi -p $BITBUCKET_CLONE_DIR -n $LATEST_COMMIT_HASH_TAG -i $BITBUCKET_BUILD_NUMBER || if test $? -eq 21; then exit 0; else exit 1; fi
            - echo 'Production Org Deployment'
            - sfDeploy mdapipackage -p $BITBUCKET_CLONE_DIR -u "$PROD_ORG_USERNAME" -s "$PROD_ORG_PASSWORD" -t $PROD_ORG_TYPE --successSHA $LATEST_COMMIT_HASH_TAG -i $BITBUCKET_BUILD_NUMBER -l RunLocalTests
          artifacts:
            - Artifacts/**
  

  custom: # Pipelines that can only be triggered manually or can be scheduled
    PullAndCommitMyChangeSet:
      - variables:  #list variable names under here
          - name: CHANGESET_NAME
          - name: COMMIT_MESSAGE
          - name: BRANCH_NAME
      - step:
          name: Checkout a git branch
          script:
            - echo 'Checking out git branch'
            - pwd
            - echo $BITBUCKET_CLONE_DIR
            - echo $CHANGESET_NAME
            - echo $COMMIT_MESSAGE
            - echo $BRANCH_NAME
            - ls -a
            - git checkout -b "feature/$BRANCH_NAME"
            - echo 'Pulling changeset and commiting it to checked out branch'
            - sfRetrieve src-format -u "$DEV_ORG_USERNAME" -s "$DEV_ORG_PASSWORD" -t $DEV_ORG_TYPE -n "$CHANGESET_NAME" -p $BITBUCKET_CLONE_DIR
            - ls -a
            - git add --all
            - git commit -m "$COMMIT_MESSAGE"
            - git push
    DeployParticularCommit:
      - variables:  #list variable names under here
          - name: COMMIT_HASH_OR_TAG
      - step:
          name: Create Artifact
          script:
            - echo 'Checking out commit $COMMIT_HASH_OR_TAG'
            - git checkout $COMMIT_HASH_OR_TAG
            - echo 'Creating a Git Diff based artifact/package'
            - sfPackages mdapi -p $BITBUCKET_CLONE_DIR -n "$COMMIT_HASH_OR_TAG" -o "$COMMIT_HASH_OR_TAG~1" -v 1.0.0.$BITBUCKET_BUILD_NUMBER || if test $? -eq 21; then exit 0; else exit 1; fi
          artifacts:
            - Artifacts/**
      - step:
          name: Deploy Artifact
          script:
            - echo 'Deploying Artifact'
            - sfDeploy mdapipackage -p $BITBUCKET_CLONE_DIR/$QA_PACKAGE_DIR -u $QA_ORG_USERNAME -s $QA_ORG_PASSWORD -t $QA_ORG_TYPE -v 1.0.0.$BITBUCKET_BUILD_NUMBER -l RunLocalTests
